### ISSUE TITLE
Blog card's not clickable

### ISSUE THREAD

**Issue by wayou** [daikiojm/daikiojm.me#83]
It's a little bit weird while the card is not clickable.

![image](https://user-images.githubusercontent.com/3783096/114176241-76e2eb80-996d-11eb-8147-01cf8dfdbb95.png)

**Comment by daikiojm** [comment]
@wayou Thank you for reporting.

**Comment by daikiojm** [comment]
fixed by  https://github.com/daikiojm/daikiojm.me/commit/e95bb05ffaae9ea612c0ad26107147dd7d4d3f5f
